#!/usr/bin/env python3
"""
Adversarial Attack Test Script

Tests the success of adversarial attacks generated by gen.py.
Performs two different validation tests and saves successful results.

Usage:
    python test.py <test_type> <original_image_path> <targeted_image_path> <control_image_path> <original_fine_class> <target_coarse_class> <epsilon>

    test_type: 1 or 2 (type of test to perform)
    original_image_path: Path to original image
    targeted_image_path: Path to targeted adversarial image
    control_image_path: Path to control image
    original_fine_class: ImageNet class ID (0-999)
    target_coarse_class: Coarse class label
    epsilon: Perturbation magnitude used
"""

import json
import logging
import sys
import warnings
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image

# Import functions from utils module
from ...utils import (
    compute_coarse_score,
    get_correct_coarse_mappings,
    get_ensemble_logits,
    get_normalize_transform,
    get_preprocess_transform,
    load_ensemble,
    load_image,
)

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)
warnings.filterwarnings("ignore", category=UserWarning)


def load_imagenet_class_names() -> dict[int, str]:
    """Load ImageNet class names from file."""
    class_names = {}
    try:
        with open("imagenet_classes/imagenet_classes.txt", "r") as f:
            for line in f:
                line = line.strip()
                if line and "," in line and not line.startswith("list"):
                    parts = line.split(", ", 1)
                    if len(parts) == 2:
                        class_id = int(parts[0])
                        class_name = parts[1]
                        class_names[class_id] = class_name
    except FileNotFoundError:
        logger.warning(
            "ImageNet class names file not found. Using class indices as names."
        )
        # Fallback: use class indices as names
        for i in range(1000):
            class_names[i] = f"class_{i}"

    return class_names


class AdversarialTester:
    """Test adversarial attacks for success validation."""

    def __init__(self, device="cuda" if torch.cuda.is_available() else "cpu"):
        self.device = device
        logger.info(f"Using device: {self.device}")

        # Standard ImageNet normalization
        self.normalize = get_normalize_transform()

        # Image preprocessing
        self.preprocess = get_preprocess_transform()

        # Load ensemble models
        self.models = load_ensemble(self.device)

        # Load 16-class coarse mappings
        self.coarse_labels, self.coarse_indices = get_correct_coarse_mappings()

        # Load ImageNet class names
        self.class_names = load_imagenet_class_names()

        logger.info("Adversarial tester ready")

    def get_top_predictions(
        self, logits: torch.Tensor, top_k: int = 1000
    ) -> tuple[list[int], list[float]]:
        """Get top-k predictions from logits."""
        probs = F.softmax(logits, dim=1)
        top_probs, top_indices = torch.topk(probs, top_k, dim=1)
        return top_indices[0].cpu().numpy().tolist(), top_probs[
            0
        ].cpu().numpy().tolist()

    def test_1_top_category_check(
        self,
        targeted_logits: torch.Tensor,
        control_logits: torch.Tensor,
        targeted_coarse_class: str,
    ) -> tuple[bool, dict[str, Any]]:
        """
        Test 1: Check if top category in targeted image contains targeted coarse category,
        and if top category in control image does not contain targeted coarse category.
        """
        logger.info("Performing Test 1: Top category check")

        # Get top predictions for both images
        targeted_top_indices, targeted_top_probs = self.get_top_predictions(
            targeted_logits
        )
        control_top_indices, control_top_probs = self.get_top_predictions(
            control_logits
        )
        # Predictions computed for testing

        # Get original coarse class indices
        targeted_coarse_indices = self.coarse_indices[
            self.coarse_labels.index(targeted_coarse_class)
        ]

        # Coarse class indices determined for testing

        # Check targeted: TOP (first) category should contain targeted coarse category
        targeted_top_prediction = targeted_top_indices[0]
        targeted_success = targeted_top_prediction in targeted_coarse_indices

        # Check control: TOP (first) category should not contain targeted coarse category
        control_top_prediction = control_top_indices[0]
        control_success = control_top_prediction not in targeted_coarse_indices

        overall_success = targeted_success and control_success

        results = {
            "test_type": 1,
            "targeted_top_indices": targeted_top_indices,
            "targeted_top_probs": targeted_top_probs,
            "control_top_indices": control_top_indices,
            "control_top_probs": control_top_probs,
            "targeted_top_prediction": targeted_top_prediction,
            "control_top_prediction": control_top_prediction,
            "targeted_coarse_indices": targeted_coarse_indices,
        }

        logger.info(
            f"Test 1 Results: Overall={overall_success}, Targeted={targeted_success}, Control={control_success}"
        )

        return overall_success, results

    def test_2_coarse_score_check(
        self,
        targeted_logits: torch.Tensor,
        control_logits: torch.Tensor,
        targeted_coarse_class: str,
    ) -> tuple[bool, dict[str, Any]]:
        """
        Test 2: Check if coarse score in targeted image is > 0 and in control image is < 0.
        """
        logger.info("Performing Test 2: Coarse score check")

        if targeted_coarse_class not in self.coarse_labels:
            logger.warning(
                f"Targeted coarse class '{targeted_coarse_class}' not found in coarse labels. Skipping Test 2."
            )
            return False, {
                "test_type": 2,
                "overall_success": False,
                "error": "Coarse class not found",
            }

        # Get coarse class index
        coarse_class_idx = self.coarse_labels.index(targeted_coarse_class)

        # Get top predictions for both images
        targeted_top_indices, targeted_top_probs = self.get_top_predictions(
            targeted_logits
        )
        control_top_indices, control_top_probs = self.get_top_predictions(
            control_logits
        )

        targeted_top_prediction = targeted_top_indices[0]
        control_top_prediction = control_top_indices[0]

        # Compute coarse scores
        targeted_coarse_score = compute_coarse_score(
            targeted_logits, coarse_class_idx, self.coarse_indices
        ).item()

        control_coarse_score = compute_coarse_score(
            control_logits, coarse_class_idx, self.coarse_indices
        ).item()

        logger.info(f"Targeted coarse score: {targeted_coarse_score}")
        logger.info(f"Control coarse score: {control_coarse_score}")

        # Check conditions
        targeted_success = targeted_coarse_score > 0
        control_success = control_coarse_score < 0

        overall_success = targeted_success and control_success

        results = {
            "test_type": 2,
            "targeted_coarse_score (Sc)": targeted_coarse_score,
            "control_coarse_score (Sc)": control_coarse_score,
            "targeted_top_indices": targeted_top_indices,
            "targeted_top_probs": targeted_top_probs,
            "control_top_indices": control_top_indices,
            "control_top_probs": control_top_probs,
            "targeted_top_prediction": targeted_top_prediction,
            "control_top_prediction": control_top_prediction,
            "targeted_coarse_indices": coarse_class_idx,
        }

        logger.info(
            f"Test 2 Results: Overall={overall_success}, Targeted={targeted_success}, Control={control_success}"
        )

        return overall_success, results

    def save_successful_results(
        self,
        test_type: int,
        original_image: torch.Tensor,
        targeted_image: torch.Tensor,
        control_image: torch.Tensor,
        targeted_logits: torch.Tensor,
        control_logits: torch.Tensor,
        test_results: dict[str, Any],
        original_image_path: str,
        epsilon: float,
        output_folder: str = "successful_attacks",
    ):
        """Save successful attack results to specified folder."""

        # Create output folder
        output_path = Path(output_folder)
        output_path.mkdir(exist_ok=True)

        # Get original image name
        original_name = Path(original_image_path).stem

        # Create timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        # Create folder for this specific attack
        attack_folder = output_path / f"{original_name}_{timestamp}"
        attack_folder.mkdir(exist_ok=True)

        # Save images
        self._save_tensor_as_image(original_image, attack_folder / "original.png")
        self._save_tensor_as_image(targeted_image, attack_folder / "targeted.png")
        self._save_tensor_as_image(control_image, attack_folder / "control.png")

        # Load ImageNet class names
        class_names = load_imagenet_class_names()

        # Extract information from test_results instead of recomputing
        if test_type == 1:
            targeted_top_indices = test_results["targeted_top_indices"]
            targeted_top_probs = test_results["targeted_top_probs"]
            control_top_indices = test_results["control_top_indices"]
            control_top_probs = test_results["control_top_probs"]
        elif test_type == 2:
            targeted_top_indices = test_results["targeted_top_indices"]
            targeted_top_probs = test_results["targeted_top_probs"]
            control_top_indices = test_results["control_top_indices"]
            control_top_probs = test_results["control_top_probs"]
        else:
            # Fallback: compute top predictions
            targeted_top_indices, targeted_top_probs = self.get_top_predictions(
                targeted_logits
            )
            control_top_indices, control_top_probs = self.get_top_predictions(
                control_logits
            )

        # Create dictionaries mapping class names to probabilities
        targeted_class_probs = {
            class_names.get(idx, f"class_{idx}"): prob
            for idx, prob in zip(targeted_top_indices, targeted_top_probs)
        }

        control_class_probs = {
            class_names.get(idx, f"class_{idx}"): prob
            for idx, prob in zip(control_top_indices, control_top_probs)
        }

        # Get original image logits and create original output
        original_logits = get_ensemble_logits(
            self.normalize(original_image), self.models
        )
        original_top_indices, original_top_probs = self.get_top_predictions(
            original_logits
        )
        original_class_probs = {
            class_names.get(idx, f"class_{idx}"): prob
            for idx, prob in zip(original_top_indices, original_top_probs)
        }

        # Create output dictionaries
        original_output = {
            "logits": original_logits.cpu().numpy().tolist(),
            "class_probabilities": original_class_probs,
            "top_indices": original_top_indices,
            "top_probs": original_top_probs,
        }

        targeted_output = {
            "logits": targeted_logits.cpu().numpy().tolist(),
            "class_probabilities": targeted_class_probs,
            "top_indices": targeted_top_indices,
            "top_probs": targeted_top_probs,
        }

        control_output = {
            "logits": control_logits.cpu().numpy().tolist(),
            "class_probabilities": control_class_probs,
            "top_indices": control_top_indices,
            "top_probs": control_top_probs,
        }

        # Add test-specific information to outputs
        if test_type == 1:
            targeted_output.update(
                {
                    "top_prediction": test_results["targeted_top_prediction"],
                    "top_probs": test_results["targeted_top_probs"],
                }
            )
            control_output.update(
                {
                    "top_prediction": test_results["control_top_prediction"],
                    "original_coarse_indices": test_results["original_coarse_indices"],
                }
            )
        elif test_type == 2:
            targeted_output.update(
                {
                    "coarse_score_Sc": test_results["targeted_coarse_score (Sc)"],
                    "top_prediction": test_results["targeted_top_prediction"],
                    "original_coarse_indices": test_results["original_coarse_indices"],
                }
            )
            control_output.update(
                {
                    "coarse_score_Sc": test_results["control_coarse_score (Sc)"],
                    "top_prediction": test_results["control_top_prediction"],
                    "original_coarse_indices": test_results["original_coarse_indices"],
                }
            )

        # Save metadata
        metadata = {
            "test_type": test_type,
            "creation_date": datetime.now().isoformat(),
            "original_image_path": original_image_path,
            "epsilon": epsilon,
        }

        # Save JSON files
        with open(attack_folder / "original_ensemble_output.json", "w") as f:
            json.dump(original_output, f, indent=2)

        with open(attack_folder / "targeted_ensemble_output.json", "w") as f:
            json.dump(targeted_output, f, indent=2)

        with open(attack_folder / "control_ensemble_output.json", "w") as f:
            json.dump(control_output, f, indent=2)

        with open(attack_folder / "metadata.json", "w") as f:
            json.dump(metadata, f, indent=2)

        logger.info(f"Successfully saved results to: {attack_folder}")
        return str(attack_folder)

    def _save_tensor_as_image(self, tensor: torch.Tensor, path: Path):
        """Save tensor as image file."""
        image_np = tensor.squeeze().detach().cpu().numpy().transpose(1, 2, 0)
        image_np = np.clip(image_np * 255, 0, 255).astype(np.uint8)
        Image.fromarray(image_np).save(path)


def test_adversarial_tensors(
    test_type: int,
    targeted_image: torch.Tensor,
    control_image: torch.Tensor,
    targeted_coarse_class: str,
    device: str = "cuda" if torch.cuda.is_available() else "cpu",
) -> tuple[bool, dict[str, Any]]:
    """Test adversarial attack tensors directly without file I/O."""

    # Initialize tester
    tester = AdversarialTester(device)

    # Get ensemble logits
    logger.info("Computing ensemble logits...")
    targeted_logits = get_ensemble_logits(
        tester.normalize(targeted_image), tester.models
    )
    control_logits = get_ensemble_logits(tester.normalize(control_image), tester.models)

    # Get prediction details for metadata
    targeted_top_indices, targeted_top_probs = tester.get_top_predictions(
        targeted_logits, top_k=5
    )
    control_top_indices, control_top_probs = tester.get_top_predictions(
        control_logits, top_k=5
    )

    targeted_top_class_id = targeted_top_indices[0]
    targeted_top_class_name = tester.class_names.get(
        targeted_top_class_id, f"class_{targeted_top_class_id}"
    )
    targeted_top_probability = targeted_top_probs[0]

    control_top_class_id = control_top_indices[0]
    control_top_class_name = tester.class_names.get(
        control_top_class_id, f"class_{control_top_class_id}"
    )
    control_top_probability = control_top_probs[0]

    # Perform test based on test_type
    if test_type == 1:
        success, results = tester.test_1_top_category_check(
            targeted_logits, control_logits, targeted_coarse_class
        )
    elif test_type == 2:
        success, results = tester.test_2_coarse_score_check(
            targeted_logits, control_logits, targeted_coarse_class
        )
    else:
        raise ValueError(f"Invalid test type: {test_type}")

    # Add prediction details to results
    results["control_prediction"] = {
        "top_class_id": control_top_class_id,
        "top_class_name": control_top_class_name,
        "top_probability": control_top_probability,
        "top_5_classes": control_top_indices[:5],
        "top_5_probabilities": control_top_probs[:5],
    }

    results["targeted_prediction"] = {
        "top_class_id": targeted_top_class_id,
        "top_class_name": targeted_top_class_name,
        "top_probability": targeted_top_probability,
        "top_5_classes": targeted_top_indices[:5],
        "top_5_probabilities": targeted_top_probs[:5],
    }

    return success, results


def main():
    """Main function to test adversarial attacks."""

    if len(sys.argv) != 8:
        print(
            "Usage: python test.py <test_type> <original_image_path> <targeted_image_path> <control_image_path> <original_fine_class> <target_coarse_class> <epsilon>"
        )
        print("  test_type: 1 or 2 (type of test to perform)")
        print("  original_image_path: Path to original image")
        print("  targeted_image_path: Path to targeted adversarial image")
        print("  control_image_path: Path to control image")
        print("  original_fine_class: ImageNet class ID (0-999)")
        print("  target_coarse_class: Coarse class label")
        print("  epsilon: Perturbation magnitude used")
        sys.exit(1)

    test_type = int(sys.argv[1])
    original_image_path = sys.argv[2]
    targeted_image_path = sys.argv[3]
    control_image_path = sys.argv[4]
    original_fine_class = int(sys.argv[5])
    targeted_coarse_class = str(sys.argv[6])
    epsilon = float(sys.argv[7])

    # Validate inputs
    if test_type not in [1, 2]:
        raise ValueError("Test type must be 1 or 2")
    if not (0 <= original_fine_class <= 999):
        raise ValueError("Original fine class must be between 0 and 999")
    if epsilon <= 0:
        raise ValueError("Epsilon must be positive")

    try:
        # Initialize tester
        logger.info("Initializing adversarial tester...")
        tester = AdversarialTester()

        # Load images
        logger.info("Loading images...")
        original_image = load_image(original_image_path, tester.device)
        targeted_image = load_image(targeted_image_path, tester.device)
        control_image = load_image(control_image_path, tester.device)

        # Get ensemble logits
        logger.info("Computing ensemble logits...")
        targeted_logits = get_ensemble_logits(
            tester.normalize(targeted_image), tester.models
        )

        control_logits = get_ensemble_logits(
            tester.normalize(control_image), tester.models
        )

        # Perform test based on test_type
        if test_type == 1:
            success, results = tester.test_1_top_category_check(
                targeted_logits, control_logits, targeted_coarse_class
            )
        elif test_type == 2:
            success, results = tester.test_2_coarse_score_check(
                targeted_logits, control_logits, targeted_coarse_class
            )
        else:
            raise ValueError(f"Invalid test type: {test_type}")

        # Save results if successful
        if success:
            output_folder = tester.save_successful_results(
                test_type,
                original_image,
                targeted_image,
                control_image,
                targeted_logits,
                control_logits,
                results,
                original_image_path,
                epsilon,
            )
            print(f"\nTest {test_type} PASSED! Results saved to: {output_folder}")
        else:
            print(f"\nTest {test_type} FAILED!")
            print(f"Results: {results}")

        return success, results

    except Exception as e:
        logger.error(f"Test failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
